# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest_creatures', '0002_auto_20170321_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalsighting',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='animalsighting',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='forest_creatures.Animal'),
        ),
    ]
